export type ProductStatus = "published" | "draft" | "archived";

export type Product = {
  id: string;
  name: string;
  sku: string;
  brand: string;
  category: string;
  sellingPrice: number;
  stock: number;
  lowStockThreshold: number;
  status: ProductStatus;
};

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Aurora X12 Smartphone",
    sku: "TC-SP-0001",
    brand: "Brand A",
    category: "Smartphones",
    sellingPrice: 44910,
    stock: 128,
    lowStockThreshold: 10,
    status: "published",
  },
  {
    id: "2",
    name: "Nova Lite Smartphone",
    sku: "TC-SP-0002",
    brand: "Brand B",
    category: "Smartphones",
    sellingPrice: 31999,
    stock: 2,
    lowStockThreshold: 5,
    status: "published",
  },
  {
    id: "3",
    name: "ProBook 14 Laptop",
    sku: "TC-LP-0007",
    brand: "Brand C",
    category: "Laptops",
    sellingPrice: 89900,
    stock: 14,
    lowStockThreshold: 5,
    status: "draft",
  },
  {
    id: "4",
    name: "SoundBeam Earbuds",
    sku: "TC-AC-0045",
    brand: "Brand D",
    category: "Accessories",
    sellingPrice: 2499,
    stock: 40,
    lowStockThreshold: 10,
    status: "published",
  },
  {
    id: "5",
    name: "USB-C Charger 20W",
    sku: "TC-AC-0031",
    brand: "Brand A",
    category: "Accessories",
    sellingPrice: 1299,
    stock: 0,
    lowStockThreshold: 10,
    status: "archived",
  },
  {
    id: "6",
    name: "VisionPro 55-inch Smart TV",
    sku: "TC-TV-0012",
    brand: "Brand E",
    category: "Televisions",
    sellingPrice: 55990,
    stock: 18,
    lowStockThreshold: 5,
    status: "published",
  },
  {
    id: "7",
    name: "Titan Mechanical Keyboard",
    sku: "TC-AC-0056",
    brand: "Brand F",
    category: "Accessories",
    sellingPrice: 4999,
    stock: 35,
    lowStockThreshold: 8,
    status: "published",
  },
  {
    id: "8",
    name: "AirFlow Wireless Mouse",
    sku: "TC-AC-0057",
    brand: "Brand G",
    category: "Accessories",
    sellingPrice: 1799,
    stock: 4,
    lowStockThreshold: 10,
    status: "published",
  },
  {
    id: "9",
    name: "UltraTab 11 Tablet",
    sku: "TC-TB-0021",
    brand: "Brand H",
    category: "Tablets",
    sellingPrice: 27999,
    stock: 22,
    lowStockThreshold: 5,
    status: "draft",
  },
  {
    id: "10",
    name: "PowerMax 20000mAh Power Bank",
    sku: "TC-AC-0060",
    brand: "Brand A",
    category: "Accessories",
    sellingPrice: 2199,
    stock: 60,
    lowStockThreshold: 15,
    status: "published",
  },
  {
    id: "11",
    name: "CrystalView Gaming Monitor",
    sku: "TC-MN-0015",
    brand: "Brand C",
    category: "Monitors",
    sellingPrice: 32990,
    stock: 9,
    lowStockThreshold: 5,
    status: "published",
  },
  {
    id: "12",
    name: "HyperDrive Gaming Mouse",
    sku: "TC-AC-0068",
    brand: "Brand F",
    category: "Accessories",
    sellingPrice: 3499,
    stock: 25,
    lowStockThreshold: 5,
    status: "archived",
  },
  {
    id: "13",
    name: "Echo Mini Bluetooth Speaker",
    sku: "TC-SP-0098",
    brand: "Brand D",
    category: "Audio",
    sellingPrice: 3999,
    stock: 12,
    lowStockThreshold: 5,
    status: "published",
  },
  {
    id: "14",
    name: "ZenBook Air Laptop",
    sku: "TC-LP-0015",
    brand: "Brand C",
    category: "Laptops",
    sellingPrice: 74900,
    stock: 7,
    lowStockThreshold: 5,
    status: "published",
  },
  {
    id: "15",
    name: "SmartWatch Pro Series",
    sku: "TC-WT-0009",
    brand: "Brand B",
    category: "Wearables",
    sellingPrice: 12999,
    stock: 30,
    lowStockThreshold: 8,
    status: "draft",
  },
  {
    id: "16",
    name: "RapidCharge USB-C Cable",
    sku: "TC-AC-0072",
    brand: "Brand A",
    category: "Accessories",
    sellingPrice: 799,
    stock: 150,
    lowStockThreshold: 20,
    status: "published",
  },
  {
    id: "17",
    name: "GalaxyView E-Reader",
    sku: "TC-ER-0004",
    brand: "Brand H",
    category: "Readers",
    sellingPrice: 15999,
    stock: 6,
    lowStockThreshold: 5,
    status: "published",
  },
  {
    id: "18",
    name: "NoiseCancel Pro Headphones",
    sku: "TC-HD-0033",
    brand: "Brand D",
    category: "Audio",
    sellingPrice: 8999,
    stock: 45,
    lowStockThreshold: 10,
    status: "published",
  },
  {
    id: "19",
    name: "SmartHome Security Camera",
    sku: "TC-IOT-0025",
    brand: "Brand E",
    category: "Smart Home",
    sellingPrice: 5999,
    stock: 3,
    lowStockThreshold: 5,
    status: "draft",
  },
  {
    id: "20",
    name: "UltraFast SSD 1TB",
    sku: "TC-ST-0018",
    brand: "Brand G",
    category: "Storage",
    sellingPrice: 8999,
    stock: 20,
    lowStockThreshold: 5,
    status: "archived",
  },
];
